repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        types: [java]
        additional_dependencies:
          - prettier@2.4.1
          - prettier-plugin-java@1.4.0
