# Default values for alfresco-acs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registryPullSecrets: quay-registry-secret

repository:
  replicaCount: 1
  image:
    repository: quay.io/alfresco/alfresco-full-content-services-community
    tag: "latest"
    pullPolicy: Always
    internalPort: 8080
  service:
    name: alfresco
    type: NodePort
    externalPort: 80
  ingress:
    path: /alfresco
  environment:
    JAVA_OPTS: " -Dsolr.base.url=/solr
      -Dsolr.secureComms=none
      -Dindex.subsystem.name=solr6"

share:
  replicaCount: 1
  image:
    repository: quay.io/alfresco/alfresco-full-share
    tag: "5.2.X"
    pullPolicy: Always
    internalPort: 8080
  service:
    name: share
    type: NodePort
    externalPort: 80
  ingress:
    path: /share

solr:
  replicaCount: 1
  image:
    repository: quay.io/alfresco/search-services
    tag: "1.2.0-SNAPSHOT"
    pullPolicy: IfNotPresent
    internalPort: 8983
  service:
    name: solr
    type: NodePort
    externalPort: 80
  ingress:
    path: /solr
  environment:
    SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive

postgresql:
  ## If true, install the postgresql chart alongside Alfresco Content Services
  enabled: true

  nameOverride: postgresql-acs
  imageTag: "9.4.12"

  postgresUser: alfresco
  postgresPassword: alfresco
  postgresDatabase: alfresco

  persistence:
    enabled: false

nginx-ingress:
  ## If true, install the nginx-ingress chart alongside Alfresco Content Services
  enabled: true