apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "content-services.fullname" . }}-repository
  labels:
    app: {{ template "content-services.fullname" . }}-repository
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.repository.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "content-services.fullname" . }}-repository
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.registryPullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.repository.image.repository }}:{{ .Values.repository.image.tag }}"
          imagePullPolicy: {{ .Values.repository.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ template "content-services.fullname" . }}-repository-configmap
          ports:
            - containerPort: {{ .Values.repository.image.internalPort }}
      initContainers:
        - name: init-postgres
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-postgresql-acs; do echo "waiting for postgres"; sleep 2; done;']
